import { UserProvider } from '@/context/UserContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
        <header>
        <h1>Blog de roberto</h1>
        <nav>
          <ul>
          <Link href="/auth/registrarse">Registrarse</Link>
          <Link href="/auth/iniciar-sesion">Iniciar sesion</Link>

          </ul>
        </nav>
        
        </header> 
          {children}
        </UserProvider>   
      </body>
    </html>
  )
}
